name: task_manager
description: A Flutter task management app with CRUD functionality.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.0
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  logger: ^2.0.3
  uuid: ^4.3.3
  intl: ^0.18.1
  flutter_slidable: ^3.0.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.4.8
  json_serializable: ^6.6.1
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
