name: task_manager
description: A Flutter task management app with CRUD functionality.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.3.3
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  logger: ^2.0.2
  uuid: ^4.1.0
  intl: ^0.18.1
  flutter_slidable: ^3.0.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true